import type { AgentMetadataV1 } from '../types'

const VUETIFY_API_KEY_INPUT = {
  type: 'env',
  env: 'VUETIFY_API_KEY',
  label: 'Vuetify MCP API key',
  secret: true,
} as const

export const builtinAgents: AgentMetadataV1[] = [
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'copilot',
    name: 'GitHub Copilot',
    description: 'Copilot Chat and Agent mode inside supported IDEs.',
    publisher: 'GitHub',
    homepage: 'https://github.com/features/copilot',
    categories: ['assistant', 'ide'],
    aliases: ['github-copilot'],
    tags: ['copilot', 'github', 'ide'],
    compatibility: {
      ides: ['code', 'code-insiders', 'cursor', 'windsurf', 'trae'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'visual-studio',
    name: 'Visual Studio',
    description: 'Visual Studio IDE with project-local MCP config support.',
    publisher: 'Microsoft',
    homepage: 'https://visualstudio.microsoft.com',
    categories: ['assistant', 'ide'],
    aliases: ['visualstudio'],
    tags: ['visual-studio', 'microsoft', 'ide'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'claude',
    name: 'Claude Desktop',
    description: 'Anthropic Claude Desktop application.',
    publisher: 'Anthropic',
    homepage: 'https://claude.ai/download',
    categories: ['assistant', 'desktop'],
    tags: ['claude', 'anthropic', 'desktop'],
    compatibility: {
      ides: ['claude'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Claude Code CLI with built-in MCP commands.',
    publisher: 'Anthropic',
    homepage: 'https://docs.anthropic.com/en/docs/claude-code',
    categories: ['assistant', 'cli'],
    tags: ['claude', 'anthropic', 'cli'],
    compatibility: {
      ides: ['claude-code'],
      scopes: ['local', 'global'],
      modes: ['remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'cursor',
    name: 'Cursor',
    description: 'Cursor IDE with MCP support.',
    publisher: 'Anysphere',
    homepage: 'https://www.cursor.com',
    categories: ['assistant', 'ide'],
    tags: ['cursor', 'ide'],
    compatibility: {
      ides: ['cursor'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'windsurf',
    name: 'Windsurf',
    description: 'Windsurf IDE with MCP support.',
    publisher: 'Codeium',
    homepage: 'https://codeium.com/windsurf',
    categories: ['assistant', 'ide'],
    tags: ['windsurf', 'codeium', 'ide'],
    compatibility: {
      ides: ['windsurf'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'continue',
    name: 'Continue',
    description: 'Continue extension for VS Code and other IDEs.',
    publisher: 'Continue',
    homepage: 'https://www.continue.dev',
    categories: ['assistant', 'extension', 'ide'],
    tags: ['continue', 'extension', 'ide'],
    compatibility: {
      ides: ['code', 'code-insiders', 'cursor', 'windsurf'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'cline',
    name: 'Cline',
    description: 'Cline extension for VS Code and compatible editors.',
    homepage: 'https://cline.bot',
    categories: ['assistant', 'extension', 'ide'],
    tags: ['cline', 'extension', 'ide'],
    compatibility: {
      ides: ['code', 'code-insiders', 'cursor', 'windsurf'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'roo',
    name: 'Roo Code',
    description: 'Roo Code extension (Agent) with MCP support.',
    homepage: 'https://github.com/RooVetGit/Roo-Code',
    categories: ['assistant', 'extension', 'ide'],
    tags: ['roo', 'extension', 'ide'],
    compatibility: {
      ides: ['code', 'code-insiders', 'cursor', 'windsurf'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'opencode',
    name: 'OpenCode',
    description: 'OpenCode CLI.',
    categories: ['assistant', 'cli'],
    tags: ['opencode', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'warp',
    name: 'Warp',
    description: 'Warp terminal with AI features and MCP ecosystem integration.',
    publisher: 'Warp',
    homepage: 'https://www.warp.dev',
    categories: ['assistant', 'terminal'],
    tags: ['warp', 'terminal'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'codex',
    name: 'Codex',
    description: 'Codex CLI.',
    publisher: 'OpenAI',
    homepage: 'https://github.com/openai/codex',
    categories: ['assistant', 'cli'],
    tags: ['codex', 'openai', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'gemini-cli',
    name: 'Gemini CLI',
    description: 'Gemini CLI.',
    publisher: 'Google',
    homepage: 'https://github.com/google-gemini/gemini-cli',
    categories: ['assistant', 'cli'],
    tags: ['gemini', 'google', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'aider',
    name: 'Aider',
    description: 'Aider coding assistant.',
    homepage: 'https://aider.chat',
    categories: ['assistant', 'cli'],
    tags: ['aider', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'firebase',
    name: 'Firebase Studio',
    description: 'Firebase Studio environment (IDX) with MCP support.',
    homepage: 'https://firebase.google.com/products/studio',
    categories: ['assistant', 'ide'],
    tags: ['firebase', 'idx', 'ide'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'jules',
    name: 'Jules',
    description: 'Jules agent.',
    categories: ['assistant'],
    tags: ['jules'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'crush',
    name: 'Crush',
    description: 'Crush agent.',
    categories: ['assistant', 'cli'],
    tags: ['crush', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'zed',
    name: 'Zed',
    description: 'Zed editor with MCP support.',
    publisher: 'Zed Industries',
    homepage: 'https://zed.dev',
    categories: ['assistant', 'ide'],
    tags: ['zed', 'ide'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'kiro',
    name: 'Kiro',
    description: 'Kiro agent.',
    categories: ['assistant', 'cli'],
    tags: ['kiro', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'amazonqcli',
    name: 'Amazon Q CLI',
    description: 'Amazon Q CLI agent.',
    publisher: 'AWS',
    homepage: 'https://aws.amazon.com/q/',
    categories: ['assistant', 'cli'],
    tags: ['amazonq', 'aws', 'cli'],
    aliases: ['amazonq', 'amazon-q-cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'firebender',
    name: 'Firebender',
    description: 'Firebender agent.',
    categories: ['assistant'],
    tags: ['firebender'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'factory',
    name: 'Factory Droid',
    description: 'Factory Droid agent.',
    categories: ['assistant'],
    tags: ['factory', 'droid'],
    aliases: ['factory-droid'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'antigravity',
    name: 'Antigravity',
    description: 'Antigravity agent.',
    categories: ['assistant'],
    tags: ['antigravity'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'mistralvibe',
    name: 'Mistral Vibe',
    description: 'Mistral Vibe agent.',
    publisher: 'Mistral AI',
    homepage: 'https://mistral.ai',
    categories: ['assistant'],
    tags: ['mistral'],
    aliases: ['mistral-vibe'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'pi',
    name: 'Pi',
    description: 'Pi agent.',
    categories: ['assistant'],
    tags: ['pi'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'jetbrains',
    name: 'JetBrains AI Assistant',
    description: 'JetBrains AI Assistant.',
    publisher: 'JetBrains',
    homepage: 'https://www.jetbrains.com/ai/',
    categories: ['assistant', 'ide'],
    tags: ['jetbrains', 'ide'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'goose',
    name: 'Goose',
    description: 'Goose agent.',
    homepage: 'https://block.github.io/goose',
    categories: ['assistant', 'cli'],
    tags: ['goose', 'cli'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'openhands',
    name: 'OpenHands',
    description: 'OpenHands autonomous agent platform.',
    publisher: 'All Hands AI',
    homepage: 'https://github.com/All-Hands-AI/OpenHands',
    categories: ['assistant', 'automation'],
    tags: ['openhands', 'automation'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'amp',
    name: 'Amp',
    description: 'Amp agent.',
    categories: ['assistant'],
    tags: ['amp'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'augment',
    name: 'Augment',
    description: 'Augment agent.',
    categories: ['assistant'],
    tags: ['augment'],
    aliases: ['augmentcode'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'junie',
    name: 'Junie',
    description: 'Junie agent.',
    categories: ['assistant'],
    tags: ['junie'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'kilocode',
    name: 'Kilo Code',
    description: 'Kilo Code agent.',
    categories: ['assistant'],
    tags: ['kilo'],
    aliases: ['kilo'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'qwen',
    name: 'Qwen Code',
    description: 'Qwen Code agent.',
    categories: ['assistant', 'cli'],
    tags: ['qwen', 'cli'],
    aliases: ['qwen-code'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'trae',
    name: 'Trae',
    description: 'Trae IDE agent support.',
    publisher: 'ByteDance',
    homepage: 'https://www.trae.ai',
    categories: ['assistant', 'ide'],
    tags: ['trae', 'ide'],
    compatibility: {
      ides: ['trae'],
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
  {
    schema: 'vuetify.mcp.agent/v1',
    id: 'trae-cn',
    name: 'Trae CN',
    description: 'Trae (China) build.',
    categories: ['assistant', 'ide'],
    tags: ['trae', 'ide'],
    compatibility: {
      scopes: ['local', 'global'],
      modes: ['package', 'remote'],
    },
    inputs: {
      vuetifyApiKey: VUETIFY_API_KEY_INPUT,
    },
  },
]
